[package]
name = "fsd28-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fsd28-lib = { path = "../fsd28-lib" }
dialoguer = "0.9"
